apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-dynamic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      volumes:
        - name: newvolume
          persistentVolumeClaim:
            claimName: deploy-dynamic-pvc
      containers:
        - name: ip-app
          image: gauthambappalige12/webpage:ipapp
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/tmp/data/"
              name: newvolume  
            