apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
spec:
  awsElasticBlockStore:
    volumeID: vol-0b26bb230fac0c4de
    fsType: xfs
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi