apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
spec:
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: nginx-dashboard
          image: gauthambappalige12/webpage:nginxdash
          ports:
            - containerPort: 80