apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
      app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shelfproject
  template:
    metadata:
      labels:
        app: shelfproject
    spec:
      containers:
      - name: shelf-container01
        image: gauthambappalige12/webpage:nginxdash
        ports:
        - containerPort: 80