apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
      - name: ipapp
        image: gauthambappalige12/webpage:ipapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ipapp
spec:
  type: ClusterIP
  selector:
    app: ip-app
  ports:
    - name: http
      port: 30002
      targetPort: 8080   

