apiVersion: v1
kind: Service
metadata:
  name: shelfproject
spec:
  ports:
  - port: 80
    nodePort: 30001
    targetPort: shelf-port
    protocol: TCP
  selector:
       app: shelfproject
  type: NodePort  